services:
  - type: web
    name: contact-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false